SECRET_KEY="secret"
COLLECTION_TOKEN="some-secret-token-master"
HELPER_SERVER_TOKEN="some-secret-token-helper"
PRIVATE_ENC_KEY="aggregation_server/keys/key_priv_master.pem"
DATASTORE_FIELD_NAMES=["age", "gender", "wealth"]
METRIC_NAMES=["histogram", "variance", "average", "sum"]
PARTNER_SERVER_IP="200.168.0.2"
PARTNER_SERVER_PORT=80
MAX_FILE_SIZE=1000
OUTPUT_FILE_PATH="./user_data/"
OUTPUT_FILE_PREFIX="user_data_"
ENCRYPT=False